timeout: 2400s
options:
  substitution_option: 'ALLOW_LOOSE'
  env:
   - TF_VAR_project=${PROJECT_ID}

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

images:
  - '${_IMAGE}'

substitutions:
  _IMAGE: 'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${TAG_NAME:-${SHORT_SHA}}'
