timeout: 2400s
options:
  substitution_option: 'ALLOW_LOOSE'
  env:
   - TF_VAR_project=${PROJECT_ID}

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

#  - name: 'docker.io/hashicorp/terraform:1.0.11'
#    args: ['init']
#    dir: ./terraform
#
#  - name: 'docker.io/hashicorp/terraform:1.0.11'
#    args: ['apply', '-auto-approve']
#    dir: ./terraform
#    timeout: 1800s

images:
  - '${_IMAGE}'

substitutions:
  _IMAGE: 'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${TAG_NAME:-${SHORT_SHA}}'
