timeout: 2400s
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'docker.io/hashicorp/terraform:1.0.11'
    dir: ./terraform
    args: ['init']

  - name: 'docker.io/hashicorp/terraform:1.0.11'
    args: ['apply', '-var', 'project=$PROJECT_ID', '-auto-approve']
    dir: ./terraform
    timeout: 1800s

images:
  - '${_IMAGE}'

substitutions:
  _IMAGE: 'eu.gcr.io/${PROJECT_ID}/${REPO_NAME}:${TAG_NAME:-${SHORT_SHA}}'