steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/authority-contribution-scraper:$SHORT_SHA', '.' ]
images:
- 'eu.gcr.io/$PROJECT_ID/authority-contribution-scraper:$SHORT_SHA'
