timeout: 2400s
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/authority-contribution-scraper:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'tag'
      - 'eu.gcr.io/$PROJECT_ID/authority-contribution-scraper:$SHORT_SHA'
      - 'eu.gcr.io/$PROJECT_ID/authority-contribution-scraper:latest'

  - name: 'docker.io/hashicorp/terraform:0.12.18'
    dir: ./terraform
    args: ['init']

  - name: 'docker.io/hashicorp/terraform:0.12.18'
    args: ['apply', '-var', 'project=$PROJECT_ID', '-auto-approve']
    dir: ./terraform
    timeout: 1800s

images:
- 'eu.gcr.io/$PROJECT_ID/authority-contribution-scraper:$SHORT_SHA'
- 'eu.gcr.io/$PROJECT_ID/authority-contribution-scraper:latest'
